#!/bin/sh



echo "File 1 contains:"
echo `comm -13 file1.txt <\( sort -nu /home/ec2-user/c217/file1.txt \)`


echo "File 2 contains:"
echo `comm -23 file1.txt <\( sort -nu file2.txt \)`




























 	



